admin_importacion_listar:
    path: /listar
    defaults: { _controller: DocumentacionBundle:Importacion:listar }

admin_importacion_nuevo:
    path: /nuevo
    defaults: { _controller: DocumentacionBundle:Importacion:nuevo }

admin_importacion_procesar:
    path: /procesar/{id}
    defaults: { _controller: DocumentacionBundle:Importacion:importar }

admin_importacion_borrar:
    path: /borrar/{id}
    defaults: { _controller: DocumentacionBundle:Importacion:borrar }
