documentacion_homepage:
    path:     /
    defaults: { _controller: DocumentacionBundle:Default:index }

personas_listar_documentos:
    path:     /documentos/{id}
    defaults: { _controller: DocumentacionBundle:Persona:documentos }
