documentacion_homepage:
    path:     /
    defaults: { _controller: DocumentacionBundle:Default:index }

login:
    path: /login
    defaults: { _controller: DocumentacionBundle:Login:login }    

personas_listar_documentos:
    path:     /documentos/{id
    defaults: { _controller: DocumentacionBundle:Persona:documentos }

documento_descargar:
    path:     /documentos/descargar/{id}
    defaults: { _controller: DocumentacionBundle:Documento:descargar }
