documentacion_homepage:
    path:     /
    defaults: { _controller: DocumentacionBundle:Default:index }

login:
    path: /login
    defaults: { _controller: DocumentacionBundle:Login:login }

login_check:
    path: /login_check

logout:
    path: /logout

principal_logueado:
    path: /principal
    defaults: { _controller: JubilacionesDeclaracionesBundle:Default:principal }
