documentacion_homepage:
    path:     /
    defaults: { _controller: DocumentacionBundle:Default:index }

login:
    path: /login
    defaults: { _controller: DocumentacionBundle:Default:login }

generar_password:
    path: /generar_password
    defaults: { _controller: DocumentacionBundle:Default:generarPassword }

login_check:
    path: /login_check

logout:
    path: /logout

principal_logueado:
    path: /principal
    defaults: { _controller: DocumentacionBundle:Default:principal }

admin_configuracion:
    path: /configuracion
    defaults: { _controller: DocumentacionBundle:Configuracion:configuracion }

admin_vaciar_tablas:
    path: /vaciar/tablas
    defaults: { _controller: DocumentacionBundle:Configuracion:vaciarTablas }
