admin_usuarios_crear_admin:
    path:     /crear/{email}/{autorizacion}
    defaults: { _controller: DocumentacionBundle:Usuario:crearAdmin }

usuarios_listar:
    path:     /listar
    defaults: { _controller: DocumentacionBundle:Usuario:listar }

usuario_cambiar_password:
    path:     /cambiar_password
    defaults: { _controller: DocumentacionBundle:Usuario:cambiarPassword }

usuario_editar_email:
    path:     /editarEmail/{id}
    defaults: { _controller: DocumentacionBundle:Usuario:editarEmail }
    requirements:
        id: \d+

admin_usuario_eliminar:
    path:     /eliminar/{id}
    defaults: { _controller: DocumentacionBundle:Usuario:eliminar }
    requirements:
        id: \d+

admin_usuario_desvincular:
    path:     /desvincular/{id}
    defaults: { _controller: DocumentacionBundle:Usuario:desvincular }
    requirements:
        id: \d+
