documentacion:
    resource: "@DocumentacionBundle/Resources/config/routing.yml"
    prefix:   /

documentacion_usuario:
    resource: "@DocumentacionBundle/Resources/config/usuario.yml"
    prefix:   /usuario

documentacion_importacion:
    resource: "@DocumentacionBundle/Resources/config/importacion.yml"
    prefix:   /importacion

documentacion_documento:
    resource: "@DocumentacionBundle/Resources/config/documento.yml"
    prefix:   /documento    

app:
    resource: '@AppBundle/Controller/'
    type: annotation
