<?php

namespace Jubilaciones\DeclaracionesBundle\Repository;

/**
 * OrganismoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConveniocuotaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllConveniocuotasAlfabeticamente() {
        $em = $this->getEntityManager();
        $dql = "SELECT c
                FROM JubilacionesDeclaracionesBundle:Conveniocuota c";
        return $em->createQuery($dql)->getResult();
    }
}
