<?php

namespace DocumentacionBundle\Repository;

/**
 * OrganismoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportacionRepository extends \Doctrine\ORM\EntityRepository
{

}
