<?php

namespace Jubilaciones\DeclaracionesBundle\Repository;

/**
 * OrganismoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganismoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrganismosAlfabeticamente() {
        $em = $this->getEntityManager();
        $dql = "SELECT o
                FROM JubilacionesDeclaracionesBundle:Organismo o
                ORDER BY o.nombre ASC";
        return $em->createQuery($dql)->getResult();
    }
}
