<?php

namespace Jubilaciones\DeclaracionesBundle\Repository;

/**
 * RepresentanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentanteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllRepresentantesAlfabeticamente() {
        $em = $this->getEntityManager();
        $dql = "SELECT r
                FROM JubilacionesDeclaracionesBundle:Representante r
                ORDER BY r.apellido ASC, r.nombres ASC ";
        return $em->createQuery($dql)->getResult();
    }

}
